print("")
print("********************************************")
print("Lab 03B, Fixing Syntax Errors")
print("100 Point Version")
print("By: JOHN SMITH") # Substitute your own name here.
print("********************************************")
print("\n")
print("You need to go through this program,")
print("find all of the syntax errors")
print("one by one, and fix them.")
print("There will be many errors.")
print("")
print("Remember, you will only see")
print("one error at a time")
print('in the "Compile Messages" window.')
print("")
print('You may wonder why an "interpreted"')
print('language has a window called "COMPILE".')
print("One reason is that jGRASP was originally")
print('created for Java (hence the "j" in jGRASP).')
print("")
print("Another reason is that modern interpreted")
print("languages actually compile the program")
print("during the first execution, while it is")
print("being interpreted, into something called")
print('"bytecode".')
print("")
print("You will notice that when you execute")
print"the same program a second time, it"
print("will execute faster.")
print("")
print("When all errors have been corrected")
print("and your output matches the provided")
print('"Sample Execution", show it to your')
print("teacher.")
