print("********************************************")
print("Lab 03A, The First Python Program")
print("100 Point Version")
print("By: ")
print("********************************************")
print("")
print("Measure today's understanding by yesterday's confusion.")
print("")
print("Bewilderment + Exposure = Obvious")
print("")
print("A poet I'm not")
print("Don't claim to be")
print("But what I wrote")
print("Did come from me. ")
print("")
print("+---------------+")
print("| +-+  @ @  +-+ |")
print("| | | ( ^ ) | | |")
print("+-+ +---U---+ +-+")
print("")
print("*  ***   ***    *****  ***  * *   * ***** *****")
print("* *   * *   *   *   * *   * * **  *   *   *    ")
print("* *   * *   *   ***** *   * * * * *   *   *****")
print("* *   * *   *   *     *   * * *  **   *       *")
print("*  ***   ***    *      ***  * *   *   *   *****")
